### PR TITLE
Added UnitTest project

### PR DESCRIPTION
**Pull request by Oceania2018**
1. Add FSharp example project back and upgrade to .net core 2.2.
2. reorganize file structure. 
3. add UnitTest project

### CODE REVIEW

**Comment by 9prady9** [comment]
@Oceania2018 I think you didn't rebase it correctly, can you please fix that.

**Comment by Oceania2018** [comment]
@9prady9 It's working now.

**Comment by 9prady9** [comment]
Hm, the rebase/merge button is still disabled on github, are you sure ?

**Comment by Oceania2018** [comment]
@9prady9 rebased

**Comment by 9prady9** [comment]
@Oceania2018 Now there are duplicate commits if I am not wrong. I am not sure how you are rebasing but there is a merge commit in this PR. I think your local branch was checked out from earlier master HEAD and not the updated one.

**Comment by Oceania2018** [comment]
@9prady9 Yes, I didn't sync before I commit. I synced it later and resolved the conflicts. My devel branch should be the right one.

**Comment by 9prady9** [comment]
Sorry to say again, but the commit history is not correct. Please look at the screenshot of github commit list of this PR.
screenshot from 2019-02-06 16-56-52

**Comment by Oceania2018** [comment]
OK, I'll redo. close this PR.

**Comment by 9prady9** [comment]
Please make sure the new branch you create is based of latest devel(arrayfire/arrayfire-dotnet).

**Comment by Oceania2018** [comment]
I delete my repo and fork again, so everything should be working.

**Comment by 9prady9** [comment]
Yup, I saw the new PR and looks good, will merge it soon.

**Pull request closed without merging**
