### PR TITLE
Upgrade Interop to arrayfire v3.6

### PR DESCRIPTION
**Pull request by Oceania2018**

### CODE REVIEW

**Comment by 9prady9** [comment]
I will test this as soon as I can tomorrow. Thanks once again for the PR!

**Comment by Oceania2018** [comment]
OK, let me know if there is anything missing. :)

**Comment by Oceania2018** [comment]
When will this PR be merged?

**Comment by 9prady9** [comment]
@Oceania2018 By end of tomorrow if I am able to run everything to run tests successfully. Sorry, we don't have a CI setup for this yet and I have to do it manually and haven't got the chance to look into it yet.

**Comment by 9prady9** [comment]
@Oceania2018 I am not sure what changed, the project is building only dlls. Any idea how do I run examples or unit tests ? I have rechecked the application type in properties of the examples and it is set ot `Console Application` but for some reason they are still building dlls instead of exes.

Actually it would be nice if you add a README for build instructions into the repo in the PR itself so that it is easy to setup and run the code for future developers/users.

**Comment by Oceania2018** [comment]
There is not `exe` for dotnetcore console application. You have to do `dotnet {path.dll}` to run.

**Comment by 9prady9** [comment]
I was able to run the examples the way you suggested but I don't see any output at all for unit test using the same procedure. Are tests run differently ?

Another query I have been wondering is - do we have to come down to command line to run the examples. Can the projects be setup in a fashion to enable running them VS IDE ?

I am definitely not a dotnet expert but that is definitely not close to the mainline approach of how applications run on Windows desktop. I believe a simple README would help a lot for anyone using these examples, be it newbies or advanced users.

**Comment by Oceania2018** [comment]
You don't have to be in VS IDE, just need dotnetcore SDK, then you run in PowerShell or CMD. I'll update README if I have a chance.

**Comment by 9prady9** [comment]
Ok, merging it then. Please don't forget to the add the README. Once again, thank you.

Misc: dotnetcore seems to have an odd way of running things. Have to read up on it sometime later.

**Comment by Oceania2018** [comment]
There are several ways to do unit test, I choose the simplest one of Microsoft Unit Test, it works with many other third building tools. Could we make the process automatically like what I've done in many of my projects. https://ci.appveyor.com/project/Haiping-Chen/tensorflow-net. It builds, tests and deploy.

**Comment by 9prady9** [comment]
Yes, I have thought about CI, but I wasn't sure on how to get started. You are welcome send PRs for those too if you are interested in it.

**Comment by 9prady9** [comment]
@Oceania2018 Also, I moved all developement to master branch from now. please raise PRs against that branch itself. Whenever there will be a release, we can tag it accordingly.

**Comment by Oceania2018** [comment]
OK, I'll work on the `dev` branch. I'm glad to contribute to the `arrayfire-dotnet` project. I'm really a `open source` fan and commit to many projects. And also I created my own open source tech org [SciSharp STACK](https://github.com/SciSharp) which has done some awesome projects for .NET ecosystem.

**Comment by 9prady9** [comment]
We are glad we have contributions coming into this wrapper. It was dormant for quite a while to be honest.

Please make sure you checkout new branches based of master so that the `rebase-merge` we do in PR will create clean and linear commit history. That is the reason I removed `devel` branch completely - to avoid one extra step - `fork -> devel -> master` and then tags when released.

**Pull request merged**
