### PR TITLE
Upgrade ArrayFire to .NET Standard 2.0.

### PR DESCRIPTION
**Pull request by Oceania2018**
HelloWorld to .NET Core 2.2
Unified to .NET Core 2.2
F# project to .NET Framework 4.7

### CODE REVIEW

**Comment by Oceania2018** [comment]
.NET Core is changed totally, it's cross-platform, run on Windows, Linux and MacOS. `AssemblyInfo.cs` is not needed anymore. You can clone my branch to run it before merging.

**Comment by 9prady9** [comment]
@Oceania2018 Thank you for the explanation. I will try it out and merge it as soon as I can.

**Comment by Oceania2018** [comment]
@9prady9, I’m not familiar with F#, but I can try. What does AutoGen do? Does it only generate then dll entry interface?

**Comment by 9prady9** [comment]
@Oceania2018 I am no clue, in fact. I am just running on general Windows knowledge to test your changes earlier and that worked there. @royalstream Is the developer who originally started working on this wrapper. Perhaps he can answer your Qs.

**Comment by royalstream** [comment]
@Oceania2018 if you look inside the **Wrapper/Interop** folder and you see the code for all the **AF*.cs** files you'll notice they're pretty repetitive. I hate doing repetitive things by hand, so I wrote a F# program to do it for me using the C++ headers as the starting point. It could have been a Python script but at the time I settled for F#. 
For the sake of completeness I decided to share this tool it in the AutoGenTool folder. But the AutoGenTool is not part of the library, it's just a helper tool I used to generate some of the library's source code.

**Pull request merged**
